<a href="https://colab.research.google.com/github/armando2039/90DaysOfCyberSecurity/blob/main/Extraer_y_Depositar_Informaci%C3%B3n.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

CELDA 1
Instalación de librerías

In [1]:
!pip install oracledb

Collecting oracledb
  Downloading oracledb-4.0.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (7.8 kB)
Requirement already satisfied: cryptography>=3.2.1 in /usr/local/lib/python3.12/dist-packages (from oracledb) (49.0.0)
Requirement already satisfied: typing_extensions>=4.14.0 in /usr/local/lib/python3.12/dist-packages (from oracledb) (4.15.0)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from cryptography>=3.2.1->oracledb) (2.0.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=2.0.0->cryptography>=3.2.1->oracledb) (3.0)
Downloading oracledb-4.0.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (2.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 28.9 MB/s eta 0:00:00
Installing collected packages: oracledb
Successfully installed oracledb-4.0.1

CELDA 2
Importación de librerías

In [3]:
import pandas as pd
import requests
import oracledb

CELDA 3
Configuración de las URLs REST

In [4]:
BASE_URL = "https://g0c48bf361ffab9-dbam01061256.adb.mx-queretaro-1.oraclecloudapps.com/ords/sample__m01061256"

url_customers = f"{BASE_URL}/demo_customers/?limit=10000"
url_orders = f"{BASE_URL}/demo_orders/?limit=10000"
url_order_items = f"{BASE_URL}/demo_order_items/?limit=10000"
url_product_info = f"{BASE_URL}/demo_product_info/?limit=10000"
url_states = f"{BASE_URL}/demo_states/?limit=10000"

CELDA 4
Función para extraer datos desde REST

In [7]:
def obtener_tabla(url):
    """
    Descarga una tabla publicada mediante Oracle REST Data Services
    y la devuelve como un DataFrame de pandas.
    """
    respuesta = requests.get(url)
    respuesta.raise_for_status()

    datos_json = respuesta.json()

    return pd.DataFrame(datos_json["items"])

CELDA 5
Extraer las cinco tablas

In [8]:
df_customers = obtener_tabla(url_customers)
df_orders = obtener_tabla(url_orders)
df_order_items = obtener_tabla(url_order_items)
df_product_info = obtener_tabla(url_product_info)
df_states = obtener_tabla(url_states)

CELDA 6
Verificar que los datos fueron extraídos

In [9]:
print("Clientes:", df_customers.shape)
print("Órdenes:", df_orders.shape)
print("Detalle Órdenes:", df_order_items.shape)
print("Productos:", df_product_info.shape)
print("Estados:", df_states.shape)

Clientes: (7, 15)
Órdenes: (10, 7)
Detalle Órdenes: (49, 6)
Productos: (10, 12)
Estados: (51, 3)

CELDA 7
Mostrar las primeras filas

In [10]:
display(df_customers.head())

display(df_orders.head())

display(df_order_items.head())

display(df_product_info.head())

display(df_states.head())

,customer_id,cust_first_name,cust_last_name,cust_street_address1,cust_street_address2,cust_city,cust_state,cust_postal_code,cust_email,phone_number1,phone_number2,url,credit_limit,tags,links
0,1,John,Dulles,45020 Aviation Drive,None,Sterling,VA,20166,john.dulles@email.com,703-555-2143,703-555-8967,http://www.johndulles.com,1000,None,"[{'rel': 'self', 'href': 'https://g0c48bf361ff..."
1,2,William,Hartsfield,6000 North Terminal Parkway,None,Atlanta,GA,30320,None,404-555-3285,None,None,1000,REPEAT CUSTOMER,"[{'rel': 'self', 'href': 'https://g0c48bf361ff..."
2,3,Edward,Logan,1 Harborside Drive,None,East Boston,MA,02128,None,617-555-3295,None,None,1000,REPEAT CUSTOMER,"[{'rel': 'self', 'href': 'https://g0c48bf361ff..."
3,4,Frank,OHare,10000 West OHare,None,Chicago,IL,60666,None,773-555-7693,None,None,1000,None,"[{'rel': 'self', 'href': 'https://g0c48bf361ff..."
4,5,Fiorello,LaGuardia,Hangar Center,Third Floor,Flushing,NY,11371,None,212-555-3923,None,None,1000,None,"[{'rel': 'self', 'href': 'https://g0c48bf361ff..."

,order_id,customer_id,order_total,order_timestamp,user_name,tags,links
0,1,7,1890,2026-05-04T05:56:17Z,DEMO,None,"[{'rel': 'self', 'href': 'https://g0c48bf361ff..."
1,2,1,2380,2026-05-18T05:56:17Z,DEMO,LARGE ORDER,"[{'rel': 'self', 'href': 'https://g0c48bf361ff..."
2,3,2,1640,2026-05-29T05:56:17Z,DEMO,None,"[{'rel': 'self', 'href': 'https://g0c48bf361ff..."
3,4,5,1090,2026-05-31T05:56:17Z,DEMO,None,"[{'rel': 'self', 'href': 'https://g0c48bf361ff..."
4,5,6,950,2026-06-10T05:56:17Z,DEMO,None,"[{'rel': 'self', 'href': 'https://g0c48bf361ff..."

,order_item_id,order_id,product_id,unit_price,quantity,links
0,100,1,1,50,10,"[{'rel': 'self', 'href': 'https://g0c48bf361ff..."
1,101,1,2,80,8,"[{'rel': 'self', 'href': 'https://g0c48bf361ff..."
2,102,1,3,150,5,"[{'rel': 'self', 'href': 'https://g0c48bf361ff..."
3,103,2,1,50,3,"[{'rel': 'self', 'href': 'https://g0c48bf361ff..."
4,104,2,2,80,3,"[{'rel': 'self', 'href': 'https://g0c48bf361ff..."

,product_id,product_name,product_description,category,product_avail,list_price,product_image,mimetype,filename,image_last_update,tags,links
0,1,Business Shirt,Wrinkle-free cotton business shirt,Mens,Y,50,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBhAQDxINEh...,image/jpeg,shirt.jpg,2026-07-08T05:56:17.782844Z,TOP SELLER,"[{'rel': 'self', 'href': 'https://g0c48bf361ff..."
1,2,Trousers,Black trousers suitable for every business man,Mens,Y,80,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAkGBwgHBgkIBw...,image/jpeg,pants.jpg,2026-07-08T05:56:17.883054Z,TOP SELLER,"[{'rel': 'self', 'href': 'https://g0c48bf361ff..."
2,3,Jacket,Fully lined jacket which is both professional ...,Mens,Y,150,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBhQSDRUTEx...,image/jpeg,jacket.jpg,2026-07-08T05:56:17.884394Z,None,"[{'rel': 'self', 'href': 'https://g0c48bf361ff..."
3,4,Blouse,Silk blouse ideal for all business women,Womens,Y,60,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBhAQEBUSEx...,image/jpeg,blouse.jpg,2026-07-08T05:56:17.885315Z,None,"[{'rel': 'self', 'href': 'https://g0c48bf361ff..."
4,5,Skirt,Wrinkle free skirt,Womens,Y,80,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAkGBwgHBgkIBw...,image/jpeg,skirt.jpg,2026-07-08T05:56:17.886258Z,None,"[{'rel': 'self', 'href': 'https://g0c48bf361ff..."

   st  state_name                                              links
0  AK      ALASKA  [{'rel': 'self', 'href': 'https://g0c48bf361ff...
1  AL     ALABAMA  [{'rel': 'self', 'href': 'https://g0c48bf361ff...
2  AR    ARKANSAS  [{'rel': 'self', 'href': 'https://g0c48bf361ff...
3  AZ     ARIZONA  [{'rel': 'self', 'href': 'https://g0c48bf361ff...
4  CA  CALIFORNIA  [{'rel': 'self', 'href': 'https://g0c48bf361ff...

CELDA 8
Exploración de los datos (depuración de los datos)

In [11]:
Limptablas = {
    "CUSTOMERS": df_customers,
    "ORDERS": df_orders,
    "ORDER_ITEMS": df_order_items,
    "PRODUCT_INFO": df_product_info,
    "STATES": df_states
}

for nombre, tabla in tablas.items():

    print("="*70)
    print(nombre)
    print("="*70)

    print("\nDimensiones:")
    print(tabla.shape)

    print("\nTipos de datos:")
    print(tabla.dtypes)

    print("\nValores nulos:")
    print(tabla.isnull().sum())

    print("\n")

======================================================================
CUSTOMERS
======================================================================

Dimensiones:
(7, 15)

Tipos de datos:
customer_id              int64
cust_first_name         object
cust_last_name          object
cust_street_address1    object
cust_street_address2    object
cust_city               object
cust_state              object
cust_postal_code        object
cust_email              object
phone_number1           object
phone_number2           object
url                     object
credit_limit             int64
tags                    object
links                   object
dtype: object

Valores nulos:
customer_id             0
cust_first_name         0
cust_last_name          0
cust_street_address1    0
cust_street_address2    6
cust_city               0
cust_state              0
cust_postal_code        0
cust_email              6
phone_number1           0
phone_number2           6
url                     6
credit_limit            0
tags                    4
links                   0
dtype: int64


======================================================================
ORDERS
======================================================================

Dimensiones:
(10, 7)

Tipos de datos:
order_id            int64
customer_id         int64
order_total         int64
order_timestamp    object
user_name          object
tags               object
links              object
dtype: object

Valores nulos:
order_id           0
customer_id        0
order_total        0
order_timestamp    0
user_name          0
tags               9
links              0
dtype: int64


======================================================================
ORDER_ITEMS
======================================================================

Dimensiones:
(49, 6)

Tipos de datos:
order_item_id     int64
order_id          int64
product_id        int64
unit_price        int64
quantity          int64
links            object
dtype: object

Valores nulos:
order_item_id    0
order_id         0
product_id       0
unit_price       0
quantity         0
links            0
dtype: int64


======================================================================
PRODUCT_INFO
======================================================================

Dimensiones:
(10, 12)

Tipos de datos:
product_id              int64
product_name           object
product_description    object
category               object
product_avail          object
list_price              int64
product_image          object
mimetype               object
filename               object
image_last_update      object
tags                   object
links                  object
dtype: object

Valores nulos:
product_id             0
product_name           0
product_description    0
category               0
product_avail          0
list_price             0
product_image          0
mimetype               0
filename               0
image_last_update      0
tags                   8
links                  0
dtype: int64


======================================================================
STATES
======================================================================

Dimensiones:
(51, 3)

Tipos de datos:
st            object
state_name    object
links         object
dtype: object

Valores nulos:
st            0
state_name    0
links         0
dtype: int64

"Realiza un proceso de depuración y limpieza de datos".
- qué columnas están vacías,
- cuáles contienen únicamente metadatos,
- cuáles no aportan al Data Warehouse,
- cuáles conviene conservar.

CELDA 9 - Limpieza de datos (Transform)

In [12]:
# DEMO_CUSTOMERS
df_customers = df_customers.drop(columns=["links"])

# DEMO_ORDERS
df_orders = df_orders.drop(columns=["links"])

# DEMO_ORDER_ITEMS
df_order_items = df_order_items.drop(columns=["links"])

# DEMO_PRODUCT_INFO
df_product_info = df_product_info.drop(columns=["links"])

# DEMO_STATES
df_states = df_states.drop(columns=["links"])

Limpieza de datos (Justificación), ¿Por qué "links"?:

- links es un campo agregado por ORDS para la navegación REST, no pertenece a la información del negocio.
- customer_id, order_id, product_id, etc., son claves necesarias.
- tags forma parte del modelo SAMPLE de Oracle APEX; aunque tenga nulos, puede considerarse un atributo del negocio.
- cust_email, phone_number2, url y cust_street_address2 contienen información opcional del cliente, no errores de datos.

CELDA 10 - Validar la limpieza

In [13]:
print("CUSTOMERS:", df_customers.columns.tolist())
print()

print("ORDERS:", df_orders.columns.tolist())
print()

print("ORDER_ITEMS:", df_order_items.columns.tolist())
print()

print("PRODUCT_INFO:", df_product_info.columns.tolist())
print()

print("STATES:", df_states.columns.tolist())

CUSTOMERS: ['customer_id', 'cust_first_name', 'cust_last_name', 'cust_street_address1', 'cust_street_address2', 'cust_city', 'cust_state', 'cust_postal_code', 'cust_email', 'phone_number1', 'phone_number2', 'url', 'credit_limit', 'tags']

ORDERS: ['order_id', 'customer_id', 'order_total', 'order_timestamp', 'user_name', 'tags']

ORDER_ITEMS: ['order_item_id', 'order_id', 'product_id', 'unit_price', 'quantity']

PRODUCT_INFO: ['product_id', 'product_name', 'product_description', 'category', 'product_avail', 'list_price', 'product_image', 'mimetype', 'filename', 'image_last_update', 'tags']

STATES: ['st', 'state_name']

CELDA 11
Subir el Wallet a Google Colab

In [14]:
from google.colab import files

uploaded = files.upload()

Saving Wallet_DBAM01061256.zip to Wallet_DBAM01061256.zip

CELDA 12
Descomprimir el Wallet

In [15]:
import zipfile
import os

wallet_zip = list(uploaded.keys())[0]

wallet_dir = "/content/wallet"

os.makedirs(wallet_dir, exist_ok=True)

with zipfile.ZipFile(wallet_zip, 'r') as zip_ref:
    zip_ref.extractall(wallet_dir)

print("Wallet extraído correctamente.")

Wallet extraído correctamente.

CELDA 13
Conectarse a Oracle Autonomous Database

Aquí debes cambiar únicamente dos datos:

Tu contraseña de la base de datos y del wallet

El nombre del servicio (HIGH)

dsn="dbam01061256_high"

In [16]:
import oracledb

connection = oracledb.connect(
    user="ADMIN",
    password="miperico-negro-esel-nUmero-0u7",
    dsn="dbam01061256_high",
    config_dir=wallet_dir,
    wallet_location=wallet_dir,
    wallet_password="miperico-negro-esel-nUmero-0u7"
)

cursor = connection.cursor()

print("✅ Conexión exitosa con Oracle Autonomous Database")

✅ Conexión exitosa con Oracle Autonomous Database

CELDA 14
Crear las tablas destino

In [17]:
def obtener_tipo_oracle(tipo):
    """
    Convierte los tipos de datos de pandas
    a tipos compatibles con Oracle.
    """

    if "int" in str(tipo):
        return "NUMBER"

    elif "float" in str(tipo):
        return "NUMBER"

    else:
        return "VARCHAR2(4000)"


tablas = {
    "DW_CUSTOMERS": df_customers,
    "DW_ORDERS": df_orders,
    "DW_ORDER_ITEMS": df_order_items,
    "DW_PRODUCT_INFO": df_product_info,
    "DW_STATES": df_states
}

for nombre, df in tablas.items():

    try:
        cursor.execute(f"DROP TABLE {nombre} PURGE")
        print(f"{nombre} eliminada.")
    except:
        pass

    columnas = []

    for columna, tipo in zip(df.columns, df.dtypes):
        columnas.append(
            f"{columna} {obtener_tipo_oracle(tipo)}"
        )

    sql = f"""
    CREATE TABLE {nombre}
    (
        {', '.join(columnas)}
    )
    """

    cursor.execute(sql)

    print(f"✅ {nombre} creada.")

connection.commit()

✅ DW_CUSTOMERS creada.
✅ DW_ORDERS creada.
✅ DW_ORDER_ITEMS creada.
✅ DW_PRODUCT_INFO creada.
✅ DW_STATES creada.

CELDA 15
Insertar los datos

In [18]:
for nombre, df in tablas.items():

    columnas = ",".join(df.columns)

    placeholders = ",".join(
        [":" + str(i+1) for i in range(len(df.columns))]
    )

    sql = f"""
    INSERT INTO {nombre}
    ({columnas})
    VALUES
    ({placeholders})
    """

    datos = []

    for fila in df.itertuples(index=False):

        datos.append(tuple(
            None if pd.isna(valor) else valor
            for valor in fila
        ))

    cursor.executemany(sql, datos)

    print(f"✅ {len(datos)} registros insertados en {nombre}")

connection.commit()

✅ 7 registros insertados en DW_CUSTOMERS
✅ 10 registros insertados en DW_ORDERS
✅ 49 registros insertados en DW_ORDER_ITEMS
✅ 10 registros insertados en DW_PRODUCT_INFO
✅ 51 registros insertados en DW_STATES

CELDA 16
Validar la carga

In [19]:
for tabla in tablas.keys():

    cursor.execute(
        f"SELECT COUNT(*) FROM {tabla}"
    )

    total = cursor.fetchone()[0]

    print(f"{tabla}: {total} registros")

DW_CUSTOMERS: 7 registros
DW_ORDERS: 10 registros
DW_ORDER_ITEMS: 49 registros
DW_PRODUCT_INFO: 10 registros
DW_STATES: 51 registros

CELDA 17
Mostrar una muestra de cada tabla desde Oracle

In [20]:
for tabla in tablas.keys():

    print("=" * 60)
    print(tabla)
    print("=" * 60)

    consulta = f"SELECT * FROM {tabla} FETCH FIRST 5 ROWS ONLY"

    df = pd.read_sql(consulta, connection)

    display(df)

============================================================
DW_CUSTOMERS
============================================================

/tmp/ipykernel_1201/2107191843.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(consulta, connection)

,CUSTOMER_ID,CUST_FIRST_NAME,CUST_LAST_NAME,CUST_STREET_ADDRESS1,CUST_STREET_ADDRESS2,CUST_CITY,CUST_STATE,CUST_POSTAL_CODE,CUST_EMAIL,PHONE_NUMBER1,PHONE_NUMBER2,URL,CREDIT_LIMIT,TAGS
0,1,John,Dulles,45020 Aviation Drive,None,Sterling,VA,20166,john.dulles@email.com,703-555-2143,703-555-8967,http://www.johndulles.com,1000,None
1,2,William,Hartsfield,6000 North Terminal Parkway,None,Atlanta,GA,30320,None,404-555-3285,None,None,1000,REPEAT CUSTOMER
2,3,Edward,Logan,1 Harborside Drive,None,East Boston,MA,02128,None,617-555-3295,None,None,1000,REPEAT CUSTOMER
3,4,Frank,OHare,10000 West OHare,None,Chicago,IL,60666,None,773-555-7693,None,None,1000,None
4,5,Fiorello,LaGuardia,Hangar Center,Third Floor,Flushing,NY,11371,None,212-555-3923,None,None,1000,None

/tmp/ipykernel_1201/2107191843.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(consulta, connection)

============================================================
DW_ORDERS
============================================================

,ORDER_ID,CUSTOMER_ID,ORDER_TOTAL,ORDER_TIMESTAMP,USER_NAME,TAGS
0,1,7,1890,2026-05-04T05:56:17Z,DEMO,None
1,2,1,2380,2026-05-18T05:56:17Z,DEMO,LARGE ORDER
2,3,2,1640,2026-05-29T05:56:17Z,DEMO,None
3,4,5,1090,2026-05-31T05:56:17Z,DEMO,None
4,5,6,950,2026-06-10T05:56:17Z,DEMO,None

============================================================
DW_ORDER_ITEMS
============================================================

/tmp/ipykernel_1201/2107191843.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(consulta, connection)

   ORDER_ITEM_ID  ORDER_ID  PRODUCT_ID  UNIT_PRICE  QUANTITY
0            100         1           1          50        10
1            101         1           2          80         8
2            102         1           3         150         5
3            103         2           1          50         3
4            104         2           2          80         3

============================================================
DW_PRODUCT_INFO
============================================================

/tmp/ipykernel_1201/2107191843.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(consulta, connection)

,PRODUCT_ID,PRODUCT_NAME,PRODUCT_DESCRIPTION,CATEGORY,PRODUCT_AVAIL,LIST_PRICE,PRODUCT_IMAGE,MIMETYPE,FILENAME,IMAGE_LAST_UPDATE,TAGS
0,4,Blouse,Silk blouse ideal for all business women,Womens,Y,60,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBhAQEBUSEx...,image/jpeg,blouse.jpg,2026-07-08T05:56:17.885315Z,None
1,5,Skirt,Wrinkle free skirt,Womens,Y,80,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAkGBwgHBgkIBw...,image/jpeg,skirt.jpg,2026-07-08T05:56:17.886258Z,None
2,9,Mens Shoes,Leather upper and lower lace up shoes,Mens,Y,110,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAkGBwgHBgkIBw...,image/jpeg,shoes.jpg,2026-07-08T05:56:17.890033Z,None
3,10,Wallet,Travel wallet suitable for men and women. Seve...,Accessories,Y,50,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBhANERIUEQ...,image/jpeg,wallet.jpg,2026-07-08T05:56:17.890963Z,None
4,6,Ladies Shoes,Low heel and cushioned interior for comfort an...,Womens,Y,120,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBhQQEBIUEh...,image/jpeg,heels.jpg,2026-07-08T05:56:17.887181Z,None

============================================================
DW_STATES
============================================================

/tmp/ipykernel_1201/2107191843.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(consulta, connection)

   ST  STATE_NAME
0  AK      ALASKA
1  AL     ALABAMA
2  AR    ARKANSAS
3  AZ     ARIZONA
4  CA  CALIFORNIA

CELDA 18
Cerrar la conexión (No ejecutado)


cursor.close()
connection.close()

print("✅ ETL finalizado correctamente.")